name: Discord Push Notification

# Trigger this workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord message
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            **${{ github.actor }}** pushed to **${{ github.repository }}**
            Commit message:
            ${{ github.event.head_commit.message }}
